name: Check Pull-Request

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - run: npm ci
      - run: npm run build

      - name: Upload MacOS Bundles
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: dist/BBNotify*.dmg

      - name: Upload Windows Bundles
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: dist/BBNotify*.exe

      - name: Upload Linux Bundles
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: dist/bitbucket-notify-desktop*.snap